(lang dune 3.0)
(name backend)
(generate_opam_files true)

(package
 (name backend)
 (synopsis "Todo app backend")
 (depends
  (ocaml
   (>= 4.14))
  dune
  dream
  caqti
  caqti-lwt
  caqti-driver-postgresql
  lwt
  lwt_ppx
  yojson))
