CREATE TABLE IF NOT EXISTS todo (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  completed BOOLEAN NOT NULL DEFAULT FALSE
);

INSERT INTO todo (title) SELECT 'first todo'
WHERE NOT EXISTS (SELECT 1 FROM todo);
