CREATE TABLE IF NOT EXISTS todo (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  done INTEGER NOT NULL DEFAULT 0
);

INSERT INTO todo (title) SELECT 'first todo'
WHERE NOT EXISTS (SELECT 1 FROM todo);
